dist: trusty
before_install:
  - sudo apt-get install -y ninja-build
script:
  - git fetch --unshallow
  - git rev-list --count HEAD
  - bash -x test.sh
  - bash -x build.sh
deploy:
  provider: releases
  api_key: $ACCESS_TOKEN
  file: ../MM-control-01-build/MM-control-01.hex
  file: ../MM-control-01-build/version.h
  skip_cleanup: true
  on:
    tags: true
